package org.fasttrackit.algorithm.sandorszucs;

/**
 * @author ttritean
 * @since 9/11/2018
 */
//exemplu cu functii - TODO din clasa MediaAritmetica
public class MedieAritmetica2 {

    public static void main(String args[]) {

        //here we read the first argument given when running the program
        //the arguments are strings (so they can contain chars)
        //we convert the strings to number
        //if the arguments can not be converted to numbers- they contain characters we display a message
        int numberOne = 10;// a default number we want
        try {
            numberOne = readNumberFromArguments(args, 0);
        } catch (NumberFormatException nfe) {
            return;
        }


        //here we read the second argument -index 1 - given when running the program
        //the arguments are strings (so they can contain chars)
        //we convert the strings to number
        //if the arguments can not be converted to numbers- they contain characters we display a message
        int numberTwo = 2;//a default number we want
        try {
            numberTwo = readNumberFromArguments(args, 1);
        } catch (NumberFormatException nfe) {
            return;
        }
        //TODO - can you see the difference between the possible result generated by this class and by MedieArtimetica?
        //Case when there are no arguments given? just one argument?


        int mediaAritmetica = (numberOne + numberTwo) / 2;
        System.out.println("Media aritmentica a numerelor " + numberOne + " si " + numberTwo + " este " + mediaAritmetica);

    }

    private static int readNumberFromArguments(String[] args, int indexOfTheArgument) throws NumberFormatException {
        int numberTwo = 0;
        if (args.length > indexOfTheArgument) {
            try {
                numberTwo = Integer.parseInt(args[indexOfTheArgument]);
            } catch (NumberFormatException nfe) {
                System.out.println("The argument " + args[indexOfTheArgument] + " is not a number");
                throw nfe;
            }
        }
        return numberTwo;
    }
}
